### ISSUE TITLE
management: Suggesting a day to have Design thinking session

### ISSUE THREAD

**Issue by inidaname** [mainheartng/organization#26]
With the project brief available, I will suggesting design thinking session to help @mainheartng/product and @mainheartng/developers understand how to move forward with the project

- What is Design Thinking - https://www.interaction-design.org/literature/article/what-is-design-thinking-and-why-is-it-so-popular

If you are in support of this 👍 otherwise 👎 .

Also for those in support please add a suggested date. It should take us at least 2 to 3 hrs

**Comment by mubaraqsomuyiwa** [comment]
Design thinking session concluded with the team on 01/03/2023. It was very insightful and interactive. Although, as always there are always some thoughts not fully spoken about, this wasn't an exception

**Comment by inidaname** [comment]
This will remain open
