### ISSUE TITLE
Will be attending the Wednesday meeting

### ISSUE THREAD

**Issue by inidaname** [mainheartng/organization#8]
Discuss here topics you would want to be on the meeting agenda. Indicate with 👍 if you will be attending the meeting or 👎 if otherwise

**Comment by inidaname** [comment]
Among other topics I will also be touching on the system design

For system design
- Why we are using some of the dependencies
- How we will follow best practices
- Approaching vul­ner­a­bility of the system
- Speeding up the responses
- Storage and data sanitization

**Comment by inidaname** [comment]
Other topics will also touch on
- Design pattern to follow
- Time frame and milestones
- Project Roadmap
- How to communicate

**Comment by inidaname** [comment]
This will be moved to the wednesday agenda of Feb 1st

**Comment by inidaname** [comment]
Another agenda to the list @mainheartng/organization 

MVP for the product and I would love to have @KelvinthePM input on this during the meeting

**Comment by KelvinthePM** [comment]
Pls what time is set for the meeting??

**Comment by inidaname** [comment]
@KelvinthePM the meeting time is set for between 8 to 9pm
